### ISSUE TITLE
issue downloading videos

### ISSUE THREAD

**Issue by BananasGoMoo** [Flkalas/TwitterVideoAssistFirefox#2]
other file formats will download but when i try to download a video, when i click the button, nothing happens.

I get this in the console too: 
![image](https://user-images.githubusercontent.com/1610384/62643354-a883f380-b8fc-11e9-88a7-3d6d0a249977.png)

**Comment by hnarsha** [comment]
+1 same issue on Firefox used in Mac as well. Broken after the recent Aug 7 2019 update

**Comment by Flkalas** [comment]
Many people send to me the error, and I just published fixed version!

Wait an hour or forced update please.

If error still happen, reopen this issue please.
